# Generated by Django 3.2.6 on 2021-08-19 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interval', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', related_query_name='target', to='scheduler.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, help_text='Baz was successfully finished')),
                ('baz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_bazes', to='scheduler.baz')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazes', to='scheduler.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BazSendOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('interval', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('success', models.BooleanField(default=False)),
                ('baz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bazes', to='scheduler.baz')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.customer')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bazes', to='scheduler.target')),
            ],
        ),
    ]
